# Blog settings
permalink: /blog/:title/

# Site config
name: dokoissho.sdf.org
description: Martin website
google_verification: null
url: http://dokoissho.sdf.org

source:      ./source
plugins_dir: ./plugins

# File management
include: ['.htaccess']
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'deploy', 'Makefile']

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Custom Collections
collections:
  projects:
    output: true
    layout: 'project'
  notes:
    output: true
    layout: 'note'
  logs:
    output: true
    layout: 'log'
    permalink: /log/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: 'project'
  - scope:
      path: ""
      type: notes
    values:
      layout: 'note'
  - scope:
      path: ""
      type: logs
    values:
      layout: 'log'
